[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# https://rustwasm.github.io/docs/book/reference/code-size.html
[profile.release]
opt-level = 's'
lto = true